# Leírás: 
# 1. https://www.dotnetcurry.com/dotnetcore/github-actions-for-dotnet-developers
# 2. https://github.com/microsoft/github-actions-for-desktop-apps/blob/main/.github/workflows/cd.yml
# 3. https://www.youtube.com/watch?v=VIlDni8-iWM
name: .NET

on:
  push:
    branches: [ "production-desktop" ]
  pull_request:
    branches: [ "production-desktop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
